---
title: "Modelling"
---

## TidyModelling

The [R](https://www.r-project.org) packages included in the [Tidymodels](https://www.tidymodels.org/) provide an
excellent framework for undertaking the modelling aspect of the work.

A very useful training workshop was held 2023-10-18 as part of the [R in Pharma](https://rinpharma.com/) event. [Nicola
Rennie](https://nrennie.rbind.io/) has made her material is available on-line and it provides a good starting point for
applying the various modelling methodologies to prediction of Thyroid cancer.

+ [Slides](https://nrennie.github.io/r-pharma-2023-tidymodels/#/title-slide)
+ [GitHub Repo](https://github.com/nrennie/r-pharma-2023-tidymodels)

Whilst this provides an excellent introduction to the Tidy Modelling framework the book [Tidy Modeling with
R](https://www.tmwr.org/) goes deeper into the methods and options available. Another useful reference on which this
books builds is [R for Data Science (2e)](https://r4ds.hadley.nz/) which should serve as a useful reference for learning
R and adopting good practices.

### Methods to Consider

There are a wealth of options when it comes to "Machine Learning", these days even logistic regression is grouped into
the term! There are however a large number of more sophisticated methods for analysing the data. Their utility

### Model Assessment

When considering the utility of prediction there are a number of metrics that can be used to determine how useful a
model is. These focus on a number of terms which have very specific statistical meaning such as [Sensitivity and
Specificity](https://en.wikipedia.org/wiki/Sensitivity_and_specificity).

|                 | Test Positive       | Test Negative       |
|-----------------|---------------------|---------------------|
| Actual Positive | True Positive (TP)  | False Negative (FN) |
| Actual Negative | False Positive (FP) | True Negative (TN)  |

There are a wealth of metrics based on combinations of these True/False Positive/Negative including precision, recall
and so forth (refer to the above linked article for further details).

### Receiver Operating Characteristics

The [Receiver Operating Characteristic (ROC)](https://en.wikipedia.org/wiki/Receiver_operating_characteristic) is a
useful graphical tool for potting the false positive rate v's the true positive rate (sensitivity).
