---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Thyroid Cancer Prediction

<!-- badges: start -->
<!-- badges: end -->

The goal of Thyroid Cancer Prediction is to investigate and predict malignant thyroid nodules.

## GitHub Pages

This project includes a website which is written in [Quarto](https://quarto.org) under the `doc/` directory and
published via GitHub Pages.

This includes summaries of the data as the data itself can not which can not be included in the repository.

### Setup

Symbolic links to the `r/` and `data/` directories that reside at the top level of this repository are required within
the `doc/` directory.

#### Linux/OSX

```bash
cd docs
ln -s ../r .
ln -s ../data .
```

#### Windows

```bash
cd docs
mklink /d r ..\r
mklink /d data ..\data
```

### Updating Pages

In order to update the website you need to publish them locally using the [`quarto
publish`](https://quarto.org/docs/publishing/github-pages.html#publish-command) command.

After making any modifications to `.qmd` files you therefore need to run.

```bash
cd docs
quarto publish
```

Note you do _not_ have to include the `_site/` directory in the GitHub repository. Running the above commands includes
these in a separate branch (`gh-pages`) and pushes the changes to GitHub.
