---
title: "Data"
---

Details of the data set.

## Data Description

### Source

The data is derived from specialist Thyroid cancer units where patients presenting with symptoms (e.g. nodules) are
assessed in greater detail and decisions are made as to whether imaging or further biopsies are required.

### Data

An ASCII CSV file (`Thy3000_DATA_LABELS_Raw.csv`) with data on 584 cases has been provided. There is no data dictionary
defining what each field is nor its type available yet.

| **Variable** | **Type** | **Description** |
| `Record ID` | | Unique identifier. |
| `Data Access Group` | | |
| `Study ID` | | |
| `1.1 Date of referral` | | |
| `1.2 Which clinic was the patient recruited from?`  | | |
| `If Other` | | |
| `1.3. The date the patient was seen in clinic` | | |
| `1.4 Referral source` | | |
| `"If Other` | | |
| `please specify"` | | |
| `"1.4.1 If GP` | | |
| `was it 2-week wait referral?"`  | | |
| `1.5. Presentation` | | |
| `Complete?`  | | |
| `2.1. Age of the patient when seen in clinic` | | |
| `2.2. Body Mass Index of patient` | | |
| `2.3. Smoking status` | | |
| `2.4. Previous neck irradiation` | | |
| `2.5 American Society of Anaesthesiologist (ASA) score` | | |
| `Complete?`  | | |
| `3.1. Presentation (choice=Neck symptoms)` | | |
| `3.1. Presentation (choice=Incidental lesion on imaging)` | | |
| `3.1. Presentation (choice=HypErthyroidism on thyroid function test)` | | |
| `3.1. Presentation (choice=HypOthyroidism on thyroid function test)` | | |
| `3.1. Presentation (choice=Symptoms of abnormal thyroid function)` | | |
| `3.1. Presentation (choice=Not known)` | | |
| `3.1. Presentation (choice=Other)` | | |
| `"If other` | | |
| `please specify"` | | |
| `3.1.1 Symptomatology (choice=No symptoms)` | | |
| `"3.1.1 Symptomatology (choice=Neck lump (noted by patient` | | |
| `family or doctor))"` | | |
| `3.1.1 Symptomatology (choice=Compressive symptoms (breathing or swallowing difficulty or voice change))` | | |
| `3.1.1 Symptomatology (choice=Symptoms of thyroid dysfunction)` | | |
| `3.1.1 Symptomatology (choice=Other)` | | |
| `"If other` | | |
| `please specify"` | | |
| `3.1.2 Was this nodule found incidentally on imaging?`  | | |
| `"If yes` | | |
| `what imaging"` | | |
| `3.2 Clinical Assessment` | | |
| `3.2.1 Retrosternal on clinical examination` | | |
| `3.2.2 Palpable lymphadenopathy` | | |
| `3.2.3 Patient perception of rapid growth of nodule` | | |
| `3.4 Thyroid function tests done within 3 months of presentation to clinic` | | |
| `3.5 Ultrasound performed` | | |
| `3.5.1 Reported maximum diameter of the largest thyroid nodule on ultrasound in millimetres` | | |
| `3.5.2 Description of thyroid nodule(s) on ultrasound` | | |
| `"3.5.3 If Ultrasound performed` | | |
| `U stage reported: "` | | |
| `"3.5.4 If Ultrasound performed` | | |
| `TIRADS reported "` | | |
| `"3.5.5 If Ultrasound performed` | | |
| `was lymphadenopathy documented"` | | |
| `3.5.6 Elastography performed` | | |
| `3.5.7 CT neck performed` | | |
| `"3.5.8 If CT neck performed` | | |
| `reason for performing it (choice=Extrathyroid extention/local invasion)"` | | |
| `"3.5.8 If CT neck performed` | | |
| `reason for performing it (choice=Retrosternal extension/plan surgical approach)"` | | |
| `"3.5.8 If CT neck performed` | | |
| `reason for performing it (choice=Extent of lymphadenopathy)"` | | |
| `"3.5.8 If CT neck performed` | | |
| `reason for performing it (choice=Tracheal compression)"` | | |
| `"3.5.8 If CT neck performed` | | |
| `reason for performing it (choice=Not known)"` | | |
| `"3.5.8 If CT neck performed` | | |
| `reason for performing it (choice=Unrelated to thyroid pathology)"` | | |
| `3.5.9 MRI neck performed` | | |
| `"3.5.10 If MRI neck performed` | | |
| `reason for performing it (choice=Extrathyroid extention/local invasion)"` | | |
| `"3.5.10 If MRI neck performed` | | |
| `reason for performing it (choice=Retrosternal extension/plan surgical approach)"` | | |
| `"3.5.10 If MRI neck performed` | | |
| `reason for performing it (choice=Extent of lymphadenopathy)"` | | |
| `"3.5.10 If MRI neck performed` | | |
| `reason for performing it (choice=Tracheal compression)"` | | |
| `"3.5.10 If MRI neck performed` | | |
| `reason for performing it (choice=Not known)"` | | |
| `"3.5.10 If MRI neck performed` | | |
| `reason for performing it (choice=Unrelated to thyroid pathology)"` | | |
| `3.5.11 Iodine-123 scan performed` | | |
| `"3.6. FNA of thyroid nodule performed (either at time of ultrasound or later)"` | | |
| `"3.6.1 If FNA performed` | | |
| `was Thy or Bethesda stage reported"` | | |
| `3.6.1.1 Thy result` | | |
| `3.6.1.2 Bethesda result` | | |
| `3.7 Core biopsy performed` | | |
| `3.8 FNA of lymph node performed` | | |
| `"3.8.1 If FNA lymph node performed` | | |
| `result"` | | |
| `Complete?`  | | |
| `4.1 Initial management decision` | | |
| `4.2 Date of decision (either clinic letter or MDT date)` | | |
| `4.3 Date of surgery or start of other treatment (if interventional)` | | |
| `"4.4. In case of no intervention` | | |
| `was a routine review offered"` | | |
| `"4.4.1 If yes` | | |
| `what was the planned interval (in weeks)"` | | |
| `4.4.2 Was Ultrasound repeated at routine review?`  | | |
| `4.4.3 Was FNA repeated at routine review` | | |
| `"4.4.4 If routine review performed` | | |
| `was management strategy changed at review"` | | |
| `"4.4.4.1 If management strategy changed at review` | | |
| `revised management decision"` | | |
| `"4.4.4.2 If yes` | | |
| `reason for change in management"` | | |
| `If other` | | |
| `4.4.4.3 If no change in management decision: date last seen by 'thyroid' team` | | |
| `"4.4.4.4 If no change in management strategy at review` | | |
| `confirm management plan when last seen"` | | |
| `4.4.5 Patient was signposted to appropriate patient SUPPORT organisation and/or provided with written PATIENT information about thyroid nodules (including leaflets)` | | |
| `Complete?`  | | |
| `5.1 Type of thyroid surgery` | | |
| `5.1.1 Lymph node dissection done at this surgery` | | |
| `5.1.2 Pathology` | | |
| `"If other cancer/other diagnosis` | | |
| `please state"` | | |
| `Complete?`  | | |
