project:
  type: website

website:
  title: "Thyroid Cancer Prediction"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - reproducibility.qmd
      - literature.qmd
      - data.qmd
      - modelling.qmd
      - citations.qmd
      - links.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/ns-rse/thyroid-cancer-prediction
  sidebar:
    style: "floating"

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
